### ISSUE TITLE
CoronaCheck app doesn't fetch the covid test conducted for traveling

### ISSUE THREAD

**Issue by tijnbarthen** [minvws/nl-covid19-coronacheck-app-coordination#31]
On CoronaTest.nl I can find the results for my travel covid test conducted on 1 July 2021. However, on the coronacheck app it only finds a regular covid test taken at the GGD on 25 June 2021. This seems like the only way to reach someone.

**Comment by th0mk** [comment]
You can call:
0800-1421 (free).
Available Monday till Sunday 08.00 a.m. - 08.00 p.m.

Or send an e-mail to:
helpdesk@coronacheck.nl
