### ISSUE TITLE
People tested positive >6 months ago and got their Pfizer shot don't show up as fully vaccinated

### ISSUE THREAD

**Issue by rsalimans47** [minvws/nl-covid19-coronacheck-app-coordination#32]
### Describe the bug, issue or concern

A clear and concise description of what the bug, issue or concern is is.

I got tested positive for COVID-19 last December, and just got my Pfizer shot.
After fetching my data, the app tells my that I'm not fully vaccinated (thus I don't get the Dutch QR code and internationally I don't show up as fully vaccinated)

### To Reproduce
1. Get Corona (more than 6 months ago :))
2. Get vaccinated
3. Fetch data from DigiD

### Expected behavior
I expected to get both my Dutch QR code and show up as fully vaccinated (1 out of 1 instead of 1 out of 2) in the International one.

### Screenshots

**Smartphone (please complete the following information):**
 - Device: 
 - OS: iOS
 - Browser Safari
 - Version 2.1.3

### Additional context

Happy to help in case there are any questions!

### Governance
- [X ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by nicktencate** [comment]
Hi, if your data is incomplete or missing please contact the vaccination provider.

https://coronacheck.nl/en/faq

**Comment by rsalimans47** [comment]
😂 thousands of people gave a 1 star review on the App Store for exactly this problem. This is your responsibility to fix, not the citizens' who do everything like they are told to. Not acceptable. On behalf of everyone who is struggling with this (which is A LOT of people) I will keep pushing until something is done about it, because promises are simply not kept here.
