### ISSUE TITLE
First character from name may not be a letter

### ISSUE THREAD

**Issue by Bloemendaal** [minvws/nl-covid19-coronacheck-app-coordination#33]
### Describe the bug, issue or concern

For some reason the app displays `_` as first 'letter' of my mother's lastname. 

### Expected behavior
The app should trim any special characters, so only letters can be displayed.

### Screenshots

![IMG-20210708-WA0002.jpg](https://user-images.githubusercontent.com/1348606/124959459-811f8f00-e01b-11eb-8f82-e8e293257cf2.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A3
 - OS: Android 11

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by nicktencate** [comment]
Hi Bloemendaal,

This is the expected behavior. The last name initial has been left out for privacy reasons. More information can be found here: https://github.com/minvws/nl-covid19-coronacheck-app-coordination/tree/main/architecture/identity
