### ISSUE TITLE
Recovery certificates > 180 days old should be valid as well

### ISSUE THREAD

**Issue by rsalimans47** [minvws/nl-covid19-coronacheck-app-coordination#34]
Can be closed, works now after a couple of days. Might be worth it to tell people that this takes a couple of days until it shows as fully vaccinated.

Sorry and good luck!

**Comment by rsalimans47** [comment]
To be clear, I also had 1 vaccine shot, which should be enough when you've been tested positive before. The app says otherwise when I retrieve my vaccine data.

**Comment by nicktencate** [comment]
Thanks for the feedback
