### ISSUE TITLE
Feature Request: Possibility to Remove Certificates

### ISSUE THREAD

**Issue by hacdias** [minvws/nl-covid19-coronacheck-app-coordination#35]
### Describe the bug, issue or concern

Cannot remove old certificates.

### To Reproduce

N/A

### Expected behavior

Possibility to remove old certificates.

### Screenshots

N/A.

### Additional context

Since we can't remove old certificates, the interface quickly gets cluttered with so much information. Needing to navigate 10 certificates to find the right one is not great, when most of them are invalid.

I would suggest to just add an option to remove certificates.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by nicktencate** [comment]
Not sure what part of the repo or app you are referring too? Can you add more information?

**Comment by hacdias** [comment]
Hello!

I opened the issue here because it refers to both Android and iOS apps. 

It would be great if there's a way to remove certificates from the app. 

For example:

![image](https://user-images.githubusercontent.tcom/5447088/126443219-5696c311-52a9-4956-b6f1-132998bdb37e.png)

I want to remove that test certificate as it is old and cannot be used anywhere. How do I remove it? Is it possible?

Thanks

**Comment by hacdias** [comment]
Example Germany app:

![image](https://user-images.githubusercontent.com/5447088/126445871-2c46c9b5-81c4-4ec0-b6ad-cfd70f829490.png)

**Comment by ijansch** [comment]
I think they get auto removed after a few days now. Can you confirm?

**Comment by hacdias** [comment]
They did not get auto removed after over 15 days. I just reinstalled the app and installed again...

**Comment by ijansch** [comment]
Let me know if you still have that problem; these days they should be removed when they are no longer relevant.
