### ISSUE TITLE
Serious issue

### ISSUE THREAD

**Issue by julian08100** [minvws/nl-covid19-coronacheck-app-coordination#37]
The CoronaCheck app only allows you to create a QR code for the Netherlands 14 days after full vaccination. The system to stop someone from creating a QR code within the 14 days can be glitched. When you change the time of the device (on iOS and maybe Android, I did not test that) the QR code becomes available!!
Please fix this asap.

**Comment by nicktencate** [comment]
Hi Julian,

The QR will indeed become visible but it will not result in a green screen on the scanner apps. The validity and other information contained in the QR cannot be changed on the mobile device.

Kind regards,
Nick

**Comment by noci2012** [comment]
There is a technical solution. Include the timestamp of generating the QR (on screen) and verify that time of scanned QR is near the local time of the scanner. 

That should prevent time travel.  maybe allow for a short period to allow for manual setups with a slight deviation.
Also use the UTC timestamps not local time.
