### ISSUE TITLE
This app excludes children and adults that are not vaccinated from public events for no valid reason.

### ISSUE THREAD

**Issue by onnoverschuuren** [minvws/nl-covid19-coronacheck-app-coordination#41]
To all developers of this app...

This app is used for forcing people to fully comply with the goverment narrative. 

Don't wait until it registers your third (bootster) "vaccine" shot.
Don't wait until it registers your co2 footprint and forces you to stop traveling.
It is not called for nothing the "green" certificate.

Please wake up!

This app makes me sick!

**Comment by nicktencate** [comment]
Hi Onno,

We simply develop the app and are not in charge of policy.

Also - Everyone can use the app, you do not need to be vaccinated. If you wish to participate in events you can get tested via https://testenvoortoegang.nl/

If you have any further questions regarding policy please contact helpdesk@coronacheck.nl
