### ISSUE TITLE
Support Ubuntu Touch platform to accomodate Dutch UT users

### ISSUE THREAD

**Issue by matv1** [minvws/nl-covid19-coronacheck-app-coordination#44]
Support Ubuntu Touch platform to accomodate Dutch UT users

Ubuntu Touch does not have a Corona Ceck app available in its store (https://open-store.io), which limits its Netherlands users.
If development assistance is needed, please contact UBPorts Foundation https://ubports.com/nl/contact
Or join either our main Telegram channel (https://t.me/ubports), or the developer channel (https://t.me/UbuntuAppDevEN)

Development documentation can be found on:
https://docs.ubports.com/en/latest/appdev/index.html
And:
https://clickable.bhdouglass.com/en/latest/index.html

Templates for app development are provided for the languages Qt/QML, C++, Python, HTML, Go, Python, Rust

**Comment by noci2012** [comment]
Not just limit this to UT.    Please consider adding generic Linux Phones. Pine Phone, Librem5 etc.

**Comment by matv1** [comment]
The UBPorts foundation will also provide some vanilla Ubuntu Touch devices, if that is helpful. Please let me know. 

A reference Corona app which reads the European certificate is also available here:
https://open-store.io/app/coronaapp.de.arnef

**Comment by matv1** [comment]
Update: the previously mentioned Corona app ( https://gitlab.com/arnef/coronaapp ) has now started support for importing a NL certificate.
This does not of course negate this issue because:
- Not all users will find it (most will look for it first at https://coronacheck.nl/nl/ and will not find a link to the UT OpenStore there)
- Or if they do find it in the UT store, may not trust it as they expect it to be provided by MinVWS.
- Parties that need to check validity, may not trust it because it is different from the expected UI

On the other hand, the mentioned app code does provide a lot of the groundwork that may help expedite programming for the official app.

**Comment by matv1** [comment]
We would like very much any response on this :)

**Comment by confiks** [comment]
As far as I know, there currently aren't any official plans to build and maintain a version of the CoronaCheck for other platforms than Android or iOS.

If such plans were to be made in the future, it would of course certainly help that the groundwork is already laid. I think the biggest chance of that happening is when you reuse as much of the official code as possible, for example the [`coronacheck-mobile-core` library](https://github.com/minvws/nl-covid19-coronacheck-mobile-core) – which uses the [`coronacheck-idemix`](https://github.com/minvws/nl-covid19-coronacheck-idemix) and [`coronacheck-hcert`](https://github.com/minvws/nl-covid19-coronacheck-hcert) for domestic and European proofs respectively. 

As far as I see, those libraries are platform independent. When I look at [covcert](https://gitlab.com/arnef/covcert), which is written in the same language as those libraries, I see that most functionality is implemented from scratch. That will bring problems when details inevitably change.

**Comment by matv1** [comment]
@confiks thanks very much for taking the time to analyze this. Seems to me your description of the path forward technically, would be the right approach.

With regard to your perception official plans to build and maintain a version of the CoronaCheck for other platforms than Android or iOS: 
This is exactly what I am asking about. If such a decision was ever made: Is there any documented policy decision where I can verify that?
And if such a documented policy does exist, this bug request means to re-evaluate that. Imo, Netherlands general policies wrt the preference of supporting free, open-source software that resorts directly under European privacy laws (UBPorts foundation is registered in Germany) are pretty clear.
However, especially with software projects like this, where the Netherlands government has direct ownership, it needs to put its money where its mouth is. Even if a platform like UT only serves a small minority. Otherwise such policy preference will remain nothing more then paper and only benefits the current dominant (non-European) platforms.

So question is who will get the ball rolling from this point on?

- First, we will need a clear policy stance from MinVWS if Google and Apple platforms will be the only platforms the official CoronaCheck app will be developed for.
- Second, If @confiks is suggesting the developer of https://gitlab.com/arnef/coronaapp should tackle changing out his own cert libraries for those provided by MinVWS as a way to further ease the way for MinVWS to pick up development from there, that could an approach.

Otoh, it seems a bit unfair to ask of one private app developer from germany to do more heavy lifting for a Netherlands government app.

**Comment by matv1** [comment]
It is disappointing that it seems hard to get a response from the repository owner MinVWS here. I do not usually bump issues, but *bump*

**Comment by ijansch** [comment]
In a letter to the Eerste Kamer the minister has answered questions about supporting Linux. The letter can be found here:

https://www.rijksoverheid.nl/binaries/rijksoverheid/documenten/kamerstukken/2021/11/05/beantwoording-commissiebrief-inzake-coronacheck-app/beantwoording-commissiebrief-inzake-coronacheck-app.pdf

The gist: supporting Linux natively is not planned, but since a lot of the Linux distributions support the f-droid store, an f-droid version of the app is now available: https://f-droid.org/en/packages/nl.rijksoverheid.ctr.holder/

Hopefully this has sufficiently answered the question.
