### ISSUE TITLE
Feature Request: Apple Wallet integration

### ISSUE THREAD

**Issue by MarkSmit** [minvws/nl-covid19-coronacheck-app-coordination#48]
Would be nice if you could add the QR code to the Wallet app on iOS. It makes it easier to use and the QR code is available on the Apple Watch as well, which is handy if someone leaves their phone at home. People now use the french app for Apple Watch support and tricky websites for Wallet support.

**Comment by mvanbaak** [comment]
Any ETA/progress on this?

**Comment by maiiikell1995** [comment]
Is this being looked at? 
iOS has support for this now since iOS 15.1

**Comment by apppel** [comment]
Interested as well! But can iOS generate the QR-code on the fly?

**Comment by michaeldeborst** [comment]
Yes please! Now that we have to show the code more often it would be great to be able to have it integrated in wallet and visible through Apple Watch. Austria's green pass app has this implemented already. Apple has some documentation here for the feature. https://developer.apple.com/videos/play/wwdc2021/10089/

**Comment by nicktencate** [comment]
Exporting data from the CoronaCheck has been discussed internally and the questions required to make a proposal have been forwarded to the relevant teams (legal, privacy, security, development) but a decision has not yet been made. If implemented, the feature would only be available for the International (DCC) QR code.

**Comment by michaeldeborst** [comment]
> Exporting data from the CoronaCheck has been discussed internally and the questions required to make a proposal have been forwarded to the relevant teams (legal, privacy, security, development) but a decision has not yet been made. If implemented, the feature would only be available for the International (DCC) QR code.

Thanks for the update! Would be disappointing if its only for the international DCC, but it's better than nothing of course.

**Comment by oxan** [comment]
> If implemented, the feature would only be available for the International (DCC) QR code.

This is truly disappointing, because the Scanner app doesn't accept a Dutch DCC but prompts for the Dutch QR-code instead, so even if I don't care about the privacy implications, it's essentially useless inside the Netherlands. Please do reconsider.

**Comment by ijansch** [comment]
Apple has recently announced support for DCCs to be loaded into apple wallet. For the Dutch QR the apple wallet would need to support dynamically generated QR codes. Until the latter is made possible I’ll close this ticket as for DCCs apple now has a solution.

**Comment by MarkSmit** [comment]
@ijansch Will the solution for DCC be supported by the Dutch authority? The vaccinations needs to be verified from the Health app before you can add the QR code to the Wallet app.
