### ISSUE TITLE
Feature request: open on selected QR (or: on last used)

### ISSUE THREAD

**Issue by Auke76** [minvws/nl-covid19-coronacheck-app-coordination#52]
Usability could be improved largely with the ability to open directly on the most recent QR (booster in my case), or on the qr of choice.

 at this moment i have to manually go to "show QR code", then select "international" and thén the app still opens on the first and oldest QR code instead of the newest.

This could be improved massively so that users don't need so much clicks to get to the right code they need to show in every location they want to enter.

**Comment by ijansch** [comment]
Thanks for the suggestion. In the current version of selects the card with the highest /y, then the one with the highest x/ so if you have both a 1/2 and a 2/2 the 2/2 should be opened by default. Even if the 1/2 was loaded more recently. 

If you are not seeing this behavior please reopen and let us know which platform (iOS or android) you are using.
