### ISSUE TITLE
Solution%20Architecture.md#backend: Links werken niet naar Retrieving events by DigiD en Retrieving events by Token

### ISSUE THREAD

**Issue by kimholan** [minvws/nl-covid19-coronacheck-app-coordination#59]
### Describe the bug, issue or concern

De gelinkte documenten op https://github.com/minvws/nl-covid19-coronacheck-app-coordination/blob/main/architecture/Solution%20Architecture.md#backend zijn niet aanwezig in de repo.

{quote}
Third Party Backends
The CoronaCheck apps retrieve their event data from third party backends. Although each party is responsible for their own architecture, we defined a set of protocols that these parties must implement in order for the apps to be able to retrieve data.

There are currently 2 protocol documents, documented in the docs/ directory and written towards these third parties:

[Retrieving events by DigiD](https://github.com/minvws/nl-covid19-coronacheck-app-coordination/blob/main/docs/providing-events-by-digid.md)
[Retrieving events by Token](https://github.com/minvws/nl-covid19-coronacheck-app-coordination/blob/main/docs/providing-events-by-token.md)
{quote}

### To Reproduce

1. Ga naar https://github.com/minvws/nl-covid19-coronacheck-app-coordination/blob/main/architecture/Solution%20Architecture.md#backend
2. Klik op [Retrieving events by DigiD](https://github.com/minvws/nl-covid19-coronacheck-app-coordination/blob/main/docs/providing-events-by-digid.md) 

### Expected behavior

Ik wordt doorgestuurd naar het gevraagde document.

### Governance
- [ X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by nicktencate** [comment]
Hi. Thanks for reporting the broken links, they will be fixed soon.

In the meantime, these are the links you are looking for:

https://github.com/minvws/nl-covid19-coronacheck-provider-docs/blob/main/docs/providing-events-by-token.md
https://github.com/minvws/nl-covid19-coronacheck-provider-docs/blob/main/docs/providing-events-by-digid.md
