### ISSUE TITLE
https://github.com/minvws/nl-covid19-coronacheck-app-coordination/blob/main/architecture/x509-pinning-1.08.pdf

### ISSUE THREAD

**Issue by kimholan** [minvws/nl-covid19-coronacheck-app-coordination#60]
### Describe the bug, issue or concern

https://github.com/minvws/nl-covid19-coronacheck-app-coordination/blob/main/architecture/x509-pinning-1.08.pdf beschrijft certificaat pinning op basis zowel Stamcertificaat Staat der Nederlanden EV Root CA, als ook Staat der Nederlanden Domein Server CA 2020.

Beide CAs verlopen per 6 december 2022.

Is er een bijgewerkt document dat de situatie na 6 december 2022 beschrijft?

### To Reproduce

Zie o.a. 1.1 en 1.2 in https://github.com/minvws/nl-covid19-coronacheck-app-coordination/blob/main/architecture/x509-pinning-1.08.pdf

### Expected behavior

Hoe ziet de situatie er na 6 december 2022 uit?

### Governance
- [ X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by nicktencate** [comment]
See https://github.com/minvws/nl-covid19-coronacheck-provider-docs/blob/main/docs/certificate-guide.md
